Add --remove-uncalled-funcs
CanadaHonk/porffor pull request #127
Opened 2024-07-11 15:47 UTC by BobVarioa

Fixes most of #85. Not enabled by default but is a relatively safe optimization. It might break some indirects? (if they don't use `funcRef` somehow)

Example: 
```sh
$ ./porf -e "console.log(1)" -b --no-run
wasm size: 39234 bytes
$ ./porf -e "console.log(1)" -b --no-run --remove-uncalled-funcs
wasm size: 30360 bytes
```

Another 20% wasm size reduction for `console.log` :tada:

2024-07-21 14:56 UTC, CanadaHonk requested changes
WIP/partial review as doing some internal changes which will affect this soon(tm)

2024-07-21 14:56 UTC, CanadaHonk commented on compiler/codegen.js
> +  out.at(-1).push('funcref');
`out.at(-1)` -> `out[0]`

2024-07-21 14:56 UTC, CanadaHonk commented on compiler/codegen.js
> +  funcs[idx - importedFuncs.length].likelyIndirect = true;
`likelyIndirect` -> `referenced`?

2024-07-21 14:56 UTC, CanadaHonk commented on compiler/codegen.js
> +
Mistake?

2024-07-21 15:03 UTC, BobVarioa commented on compiler/codegen.js
> +
Yep!

2024-08-13 09:46 UTC, CanadaHonk commented
I don't think this is needed anymore with latest rewrites?

2024-08-13 14:02 UTC, BobVarioa commented
I agree yes, I'll close it now.

2024-08-13 14:02 UTC, closed without merging